version: '4'
services:
  mysqldb-product:
    image: mysql:8.3.0
    container_name: product-mysqldb
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ./mysql:/var/lib/mysql